-- Generated by tasks/refresh_db.ts

USE `19pvp_playerbots`;

DROP TABLE IF EXISTS `playerbots_fixed_roster`;
CREATE TABLE IF NOT EXISTS `playerbots_fixed_roster` (
  `guid` int unsigned NULL DEFAULT NULL,
  `team` tinyint unsigned NOT NULL,
  `slot` tinyint unsigned NOT NULL,
  `name` varchar(12) NOT NULL DEFAULT '',
  `account` varchar(32) NOT NULL DEFAULT '',
  `faction` varchar(16) NOT NULL DEFAULT '',
  `race` tinyint unsigned NOT NULL DEFAULT 0,
  `class` tinyint unsigned NOT NULL DEFAULT 0,
  `level` tinyint unsigned NOT NULL DEFAULT 19,
  `role` varchar(16) NOT NULL DEFAULT '',
  `spec` varchar(32) NOT NULL DEFAULT '',
  `replacement_priority` tinyint unsigned NOT NULL DEFAULT 0,
  `gear_profile` varchar(32) NOT NULL DEFAULT '',
  `behavior_profile` varchar(32) NOT NULL DEFAULT '',
  `enabled` tinyint(1) unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`team`, `slot`),
  UNIQUE KEY `guid_unique` (`guid`),
  UNIQUE KEY `name_unique` (`name`),
  KEY `enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `playerbots_fixed_roster` (
  `guid`,
  `team`,
  `slot`,
  `name`,
  `account`,
  `faction`,
  `race`,
  `class`,
  `level`,
  `role`,
  `spec`,
  `replacement_priority`,
  `gear_profile`,
  `behavior_profile`,
  `enabled`
) VALUES
  (NULL, 1, 1, 'Aegwynn', 'wsgbot-aegwynn', 'alliance', 1, 5, 19, 'healer', 'discipline', 5, 'wsg-priest-healer', 'wsg-healer', 1),
  (NULL, 1, 2, 'Antonidas', 'wsgbot-antonidas', 'alliance', 1, 8, 19, 'dps', 'frost', 1, 'wsg-mage-dps', 'wsg-ranged-dps', 1),
  (NULL, 1, 3, 'Lothar', 'wsgbot-lothar', 'alliance', 1, 1, 19, 'dps', 'arms', 2, 'wsg-warrior-dps', 'wsg-melee-dps', 1),
  (NULL, 1, 4, 'Alleria', 'wsgbot-alleria', 'alliance', 4, 3, 19, 'dps', 'marksman', 3, 'wsg-hunter-dps', 'wsg-ranged-dps', 1),
  (NULL, 1, 5, 'Malfurion', 'wsgbot-malfurion', 'alliance', 4, 11, 19, 'flag-carrier', 'feral', 4, 'wsg-druid-fc', 'wsg-flag-carrier', 1),
  (NULL, 2, 1, 'Velenar', 'wsgbot-velenar', 'horde', 5, 5, 19, 'healer', 'discipline', 5, 'wsg-priest-healer', 'wsg-healer', 1),
  (NULL, 2, 2, 'Kelthuzad', 'wsgbot-kelthuzad', 'horde', 5, 8, 19, 'dps', 'frost', 1, 'wsg-mage-dps', 'wsg-ranged-dps', 1),
  (NULL, 2, 3, 'Saurfang', 'wsgbot-saurfang', 'horde', 2, 1, 19, 'dps', 'arms', 2, 'wsg-warrior-dps', 'wsg-melee-dps', 1),
  (NULL, 2, 4, 'Rokhan', 'wsgbot-rokhan', 'horde', 8, 3, 19, 'dps', 'marksman', 3, 'wsg-hunter-dps', 'wsg-ranged-dps', 1),
  (NULL, 2, 5, 'Hamuul', 'wsgbot-hamuul', 'horde', 6, 11, 19, 'flag-carrier', 'feral', 4, 'wsg-druid-fc', 'wsg-flag-carrier', 1);
