-- Generated by tasks/refresh_db.ts

random_enchant_db = {
  items = {
    [15331] = { random_suffix = 0, random_property = 1067, suffixes = {  } },
    [6586] = { random_suffix = 0, random_property = 731, suffixes = {  } },
    [51994] = { random_suffix = 381, random_property = 0, suffixes = { 84, 71, 72, 68, 75, 73, 78, 79, 85 } },
    [51978] = { random_suffix = 385, random_property = 0, suffixes = { 84, 17, 68, 75, 86, 85 } },
    [51968] = { random_suffix = 382, random_property = 0, suffixes = { 84, 69, 79, 85 } },
    [51964] = { random_suffix = 383, random_property = 0, suffixes = { 71, 78, 79, 82 } },
  },
  suffix_options = {
    [84] = { id = 84, name = "of Stamina", score = 10000, enchants = { 2803 }, stats = { { id = 7, value = 10000 } } },
    [17] = { id = 17, name = "of Strength", score = 10000, enchants = { 2805 }, stats = { { id = 4, value = 10000 } } },
    [71] = { id = 71, name = "of the Bandit", score = 21036, enchants = { 2802, 2803, 2825 }, stats = { { id = 3, value = 5259 }, { id = 7, value = 5259 }, { id = 38, value = 10518 } } },
    [72] = { id = 72, name = "of the Battle", score = 14565, enchants = { 2805, 2803, 2822 }, stats = { { id = 4, value = 7266 }, { id = 7, value = 4106 }, { id = 32, value = 3193 } } },
    [68] = { id = 68, name = "of the Bear", score = 13332, enchants = { 2805, 2803 }, stats = { { id = 4, value = 6666 }, { id = 7, value = 6666 } } },
    [75] = { id = 75, name = "of the Champion", score = 15777, enchants = { 2805, 2803, 2813 }, stats = { { id = 4, value = 5259 }, { id = 7, value = 5259 }, { id = 12, value = 5259 } } },
    [69] = { id = 69, name = "of the Eagle", score = 13332, enchants = { 2803, 2804 }, stats = { { id = 5, value = 6666 }, { id = 7, value = 6666 } } },
    [73] = { id = 73, name = "of the Elder", score = 12622, enchants = { 2803, 2804, 2816 }, stats = { { id = 5, value = 5259 }, { id = 7, value = 5259 }, { id = 43, value = 2104 } } },
    [78] = { id = 78, name = "of the Monkey", score = 13332, enchants = { 2802, 2803 }, stats = { { id = 3, value = 6666 }, { id = 7, value = 6666 } } },
    [79] = { id = 79, name = "of the Moon", score = 14024, enchants = { 2804, 2803, 2806 }, stats = { { id = 5, value = 5259 }, { id = 6, value = 5259 }, { id = 7, value = 3506 } } },
    [86] = { id = 86, name = "of the Soldier", score = 15777, enchants = { 2805, 2803, 2822 }, stats = { { id = 4, value = 5259 }, { id = 7, value = 5259 }, { id = 32, value = 5259 } } },
    [85] = { id = 85, name = "of the Sorcerer", score = 16671, enchants = { 2803, 2804, 2824 }, stats = { { id = 5, value = 5259 }, { id = 7, value = 5259 }, { id = 45, value = 6153 } } },
    [82] = { id = 82, name = "of the Vision", score = 14736, enchants = { 2824, 2804, 2803 }, stats = { { id = 5, value = 4106 }, { id = 7, value = 2129 }, { id = 45, value = 8501 } } },
  },
}
