-- Command security policy:
--   level 0: no commands
--   level 1: read/query commands listed below
--   levels 2 and 3: retain access to all existing commands

UPDATE `command`
SET `security` = 2
WHERE `security` < 2;

UPDATE `command`
SET `security` = 1
WHERE `name` IN (
  'account onlinelist',
  'arena info',
  'arena lookup',
  'baninfo account',
  'baninfo character',
  'baninfo ip',
  'banlist account',
  'banlist character',
  'banlist ip',
  'character deleted list',
  'event activelist',
  'event info',
  'gm ingame',
  'gm list',
  'gobject info',
  'gobject near',
  'gobject target',
  'group list',
  'guild info',
  'help',
  'instance getbossstate',
  'instance listbinds',
  'instance stats',
  'inventory count',
  'lfg group',
  'lfg player',
  'lfg queue',
  'list auras',
  'list auras id',
  'list auras name',
  'list creature',
  'list item',
  'list object',
  'list respawns',
  'lookup',
  'lookup area',
  'lookup creature',
  'lookup event',
  'lookup faction',
  'lookup gobject',
  'lookup item',
  'lookup item set',
  'lookup map',
  'lookup map id',
  'lookup object',
  'lookup player',
  'lookup player account',
  'lookup player email',
  'lookup player ip',
  'lookup quest',
  'lookup quest id',
  'lookup skill',
  'lookup spell',
  'lookup spell id',
  'lookup taxinode',
  'lookup teleport',
  'lookup title',
  'npc info',
  'npc near',
  'npc showloot',
  'pet list',
  'pinfo',
  'server info',
  'server motd',
  'ticket closedlist',
  'ticket escalatedlist',
  'ticket list',
  'ticket onlinelist'
);
